### ISSUE TITLE
Stopped working with coordinates?

### ISSUE THREAD

**Issue by josinaldobarbosa** [renaudcerrato/static-maps-api#2]
Example:

```
StaticMap sm = new StaticMap()
                .center(-22.9035, -43.2096)
                .size(500, 200);
```

Url result: https://maps.googleapis.com/maps/api/staticmap?center=-22%2C903500%2C-58%2C383921&size=500x200

**Comment by renaudcerrato** [comment]
You need to specify a zoom or a viewport using markers :

https://maps.googleapis.com/maps/api/staticmap?center=-34%2C601234%2C-58%2C383921&zoom=5&size=500x200

**Comment by renaudcerrato** [comment]
You need to specify a zoom or a viewport:

https://maps.googleapis.com/maps/api/staticmap?center=-34%2C601234%2C-58%2C383921&zoom=5&size=500x200

Le dim. 23 oct. 2016 01:53, Josinaldo A.Barbosa notifications@github.com
a écrit :

Example:

StaticMap sm = new StaticMap()
                .center(-22.9035, -43.2096)
                .size(500, 200);

Url result:
https://maps.googleapis.com/maps/api/staticmap?center=-34%2C601234%2C-58%2C383921&size=500x200

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/renaudcerrato/static-maps-api/issues/2, or mute the
thread

**Comment by josinaldobarbosa** [comment]
worked, thank you
